### ISSUE TITLE
NullReferenceException when using BsonDeserializer.

### ISSUE THREAD

**Issue by hosaka** [joelweiss/ChangeTracking#59]
Looking at other closed issues and the `GetCurrent` function, I still thought that this is a different issue. I have a MongoDB where I keep the object, I want to only update the elements that user has changed, rather simple. My first store works okay, but if I re-fetch the objects during the same run, the MongoDB (which uses BSON underneath) fails with NRE. I can reproduce this just by using serialize/deserialize functions, writing to a local file.

```
public class SomeObject
{
    public virtual string Uid { get; set; } = string.Empty;
};

var objects = new List<SomeObject> { new SomeObject() }.AsTrackable();
objects.First().Uid = "update";

var track = objects.CastToIChangeTrackableCollection();
if (track.IsChanged)
{
    // take changed and serialize it
    var changed = track.ChangedItems.First();
    using (var stream = File.Create("file.bson"))
    {
        using var writer = new BsonBinaryWriter(stream);
        BsonSerializer.Serialize(writer, changed);
    }

    // deserialize back
    var contents = File.ReadAllBytes("file.bson");
    var obj = BsonSerializer.Deserialize<SomeObject>(contents);
}
```
The last line throws NRE and here's the stack trace.
```
   at Castle.Proxies.SomeObjectProxy.set_Uid(String value)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonSerializer.Deserialize[TNominalType](Stream stream, Action`1 configurator)
   at MongoDB.Bson.Serialization.BsonSerializer.Deserialize[TNominalType](Byte[] bytes, Action`1 configurator)
   at ArchiSymphony.ViewModels.SheetViewModel.<>c.<<get_LoadProjectFromExternal>b__2_0>d.MoveNext() in D:\wa\pls\ArchiSymphony\ArchiSymphony\ViewModels\SheetViewModel.cs:line 46
```

I don't think the issue is with proxy properties being serialized in the first place. As I explicitly control which properties on the POCO get stored in the DB, using BsonElementAttribute. I'll be honest, I don't understand why the SomeObjectProxy is being created here, as the Deserialize should return me the unproxied SomeObject instead, which I can then mark as trackable. Any hints as to what might be wrong?

Cheers,
Alex

**Comment by hosaka** [comment]
The source of the exception is the Castle `DynamicProxyGenAssembly2`

**Comment by hosaka** [comment]
Indeed, I was wrong in my assumption that the serializer only takes what's necessary. After after some trial and error, I figured that a simple IChangeTrackable<SomeObject>.GetCurrent() works perfectly well, I re-wrote my DB related code to something along the lines of:
```
var tracked = Elements.CastToIChangeTrackableCollection();
if (tracked.IsChanged){
    var proxies = tracked.ChangedItems.Concat(tracked.AddedItems);
    var changed = proxies.Cast<IChangeTrackable<SomeObject>>().Select(o => o.GetCurrent());
    SaveElementsToDb(changed); // this does the serialization
}
```
Then, consequent reads from the database caused no issues. It'd be nice to have an option to have a TrackableCollection.GetCurrent() as well though!

**Comment by joelweiss** [comment]
Hi @hosaka
```csharp
proxies.Cast<IChangeTrackable<SomeObject>>().Select(o => o.GetCurrent())
``` 
is the correct way to get pocos for serialization.

In your case `GetCurrent()` wouldn't be the result you want because it will include unchanged items as well. I don't feel like a new api will add much value.
